<html>

<head>
</head>

<body>
<?php print_r($this->data); 
echo $this->data;?>
<br/>
<a href="http://localhost/Social_Xpert/index.php/facebook/login">Login</a>
<div style="clear:both;"></div>
<div style="padding:5px;margin:5px;float:left; border: 1px solid black; width: 200px;">
    <form method="POST" action="http://localhost/Social_Xpert/index.php/facebook/feed">
        <p>Post to fanpage</p>
    	Page ID<input type="text" name="post_user_id" id="post_user_id" value="330948406958694"/>
    	<br/>
        Message<input type="text" name="post_new" id="post_new"/>
        <br/>
    	<input type="submit" name="post_new_bt" id="post_new_bt" onclick="post_wall()" value="post in wall fan page"/>
    </form>
</div>

<div style="padding:5px;margin:5px;float:left; border: 1px solid black; width: 350px;">
	<p>Select a photo to upload on Facebook Fan Page</p>
	<form method="POST" action="http://localhost/Social_Xpert/index.php/facebook/photo" enctype="multipart/form-data">
		Page ID<input type="text" value="421753514532658" name="page_id" />
        <br/>
		Message<input type="text" name="message" />
        <br/>
		Select the image: <input type="file" name="pic" />
        <br/>
		<input class="post_but" type="submit" value="Upload to my album" />
	</form>
</div>

<div style="padding:5px;margin:5px;float:left; border: 1px solid black; width: 350px;">
	<p>Select a video to upload on Facebook Fan Page</p>
	<form method="post" action="http://localhost/Social_Xpert/index.php/facebook/video" enctype="multipart/form-data">
		Page ID<input type="text" value="421753514532658" name="page_id" />
        <br/>
		Title<input type="text" value="tit" name="title" />
        <br/>
        Description<input type="text" value="des" name="description" />
        <br/>
		Select the video: <input type="file" name="vid" />
        <br/>
		<input class="post_but" type="submit" value="Upload video" />
	</form>
</div>
<div style="clear:both;"></div>
<div style="padding:5px;margin:5px;float:left; border: 1px solid black; width: 350px;">
	<p>Post milestone</p>
	<form method="post" action="http://localhost/Social_Xpert/index.php/facebook/milestone">
		Page ID<input type="text" value="421753514532658" name="page_id_mile" />
        <br/>
		Title<input type="text" value="tit" name="title_mile" />
        <br/>
                Description<input type="text" value="des" name="description_mile" />
        <br/>
		Start Time<input type="text" value="2012-08-12" name="time_mile" />
        <br/>
		<input class="post_but" type="submit" value="Post milestone" />
	</form>
</div>
<div style="clear:both;"></div>
<div style="padding:5px;margin:5px;float:left; border: 1px solid black; width: 350px;">
	<p>Post question</p>
	<form method="post" action="http://localhost/Social_Xpert/index.php/facebook/question">
		Page ID<input type="text" value="421753514532658" name="page_id_poll" />
        <br/>
		Question<input type="text" value="question" name="question" />
        <br/>
                Option 1<input type="text" value="option 1" name="op1" />
        <br/>
		Option 2<input type="text" value="option 2" name="op2" />
        <br/>
		<input class="post_but" type="submit" value="Post question" />
	</form>
</div>

</body>

</html>