<html>

<head>
<script type="text/javascript" src="js/jquery-1.7.2.js"></script>
</head>

<body>
<?php 
print_r($this->data);
?>
<br/>
<a href="http://localhost/Social_Xpert/index.php/facebook/login">Login</a>
<div style="clear:both;"></div>
<div style="padding:5px;margin:5px;float:left; border: 1px solid black; width: 200px;">
    <form method="POST" action="http://localhost/Social_Xpert/index.php/facebook/feed">
        <p>Post to fanpage</p>
    	Page ID<input type="text" name="post_user_id" id="post_user_id" value="330948406958694"/>
    	<br/>
        Message<input type="text" name="post_new" id="post_new"/>
        <br/>
    	<input type="submit" name="post_new_bt" id="post_new_bt" onclick="post_wall()" value="post in wall fan page"/>
    </form>
</div>

<div style="padding:5px;margin:5px;float:left; border: 1px solid black; width: 350px;">
	<p>Select a photo to upload on Facebook Fan Page</p>
	<form method="POST" action="http://localhost/Social_Xpert/index.php/facebook/photo" enctype="multipart/form-data">
		Page ID<input type="text" value="421753514532658" name="page_id" />
        <br/>
		Message<input type="text" name="message" />
        <br/>
		Select the image: <input type="file" name="pic" />
        <br/>
		<input class="post_but" type="submit" value="Upload to my album" />
	</form>
</div>

<div style="padding:5px;margin:5px;float:left; border: 1px solid black; width: 350px;">
	<p>Select a video to upload on Facebook Fan Page</p>
	<form method="post" action="http://localhost/Social_Xpert/index.php/facebook/video" enctype="multipart/form-data">
		Page ID<input type="text" value="421753514532658" name="page_id" />
        <br/>
		Title<input type="text" value="tit" name="title" />
        <br/>
        Description<input type="text" value="des" name="description" />
        <br/>
		Select the video: <input type="file" name="vid" />
        <br/>
		<input class="post_but" type="submit" value="Upload video" />
	</form>
</div>

<script type="text/javascript">
	function post_wall(){
//		var p=document.getElementById('post_new').value;
//		alert(p);
		var p=$('#post_new').val();
		alert(p);
		var p_id=$('#post_user_id').val();;
		$.ajax({
		  type: 'POST',
		  url: 'http://localhost/Social_Xpert/index.php/facebook/post',
		  data: ({
			page_id : p_id, 
			message : p,
		  }),
		  success: function(data) {
			alert(data);
		  }
		});
	}
</script>
</body>

</html>